@echo off
echo HELLO
echo %COLOR_BLACK%COLOR_BLACK %COLOR_RESET%
echo %COLOR_BG_WHITE%%COLOR_BLACK%COLOR_BG_WHITE COLOR_BLACK %COLOR_RESET%
echo %COLOR_BLUE%COLOR_BLUE %COLOR_RESET%
echo %COLOR_CYAN%COLOR_CYAN %COLOR_RESET%
echo %COLOR_GREEN%COLOR_GREEN %COLOR_RESET%
echo %COLOR_PURPLE%COLOR_PURPLE %COLOR_RESET%
echo %COLOR_RED%COLOR_RED %COLOR_RESET%
echo %COLOR_WHITE%COLOR_WHITE %COLOR_RESET%
echo %COLOR_YELLOW%COLOR_YELLOW %COLOR_RESET%
echo %COLOR_BRIGHTBLACK%COLOR_BRIGHTBLACK %COLOR_RESET%
echo %COLOR_BRIGHTBLUE%COLOR_BRIGHTBLUE %COLOR_RESET%
echo %COLOR_BRIGHTCYAN%COLOR_BRIGHTCYAN %COLOR_RESET%
echo %COLOR_BRIGHTGREEN%COLOR_BRIGHTGREEN %COLOR_RESET%
echo %COLOR_BRIGHTPURPLE%COLOR_BRIGHTPURPLE %COLOR_RESET%
echo %COLOR_BRIGHTRED%COLOR_BRIGHTRED %COLOR_RESET%
echo %COLOR_BRIGHTWHITE%COLOR_BRIGHTWHITE %COLOR_RESET%
echo %COLOR_BRIGHTYELLOW%COLOR_BRIGHTYELLOW %COLOR_RESET%
echo %COLOR_BG_BLACK%COLOR_BG_BLACK %COLOR_RESET%
echo %COLOR_BG_BLUE%COLOR_BG_BLUE %COLOR_RESET%
echo %COLOR_BG_CYAN%COLOR_BG_CYAN %COLOR_RESET%
echo %COLOR_BG_GREEN%COLOR_BG_GREEN %COLOR_RESET%
echo %COLOR_BG_PURPLE%COLOR_BG_PURPLE %COLOR_RESET%
echo %COLOR_BG_RED%COLOR_BG_RED %COLOR_RESET%
echo %COLOR_BG_WHITE%COLOR_BG_WHITE %COLOR_RESET%
echo %COLOR_BG_WHITE%%COLOR_BLACK%COLOR_BG_WHITE COLOR_BLACK %COLOR_RESET%
echo %COLOR_BG_YELLOW%COLOR_BG_YELLOW %COLOR_RESET%
pause