@echo off

echo "     MM!                          MMM!"  "
echo "    MMM!!       [HACKED!]        MMMMM!  "
echo "  MMMM!                           MMMMM!!"
echo "MMMMMMMM!   MMMMMMMMMMMMMMMM!   MMMM!!!! "
echo "!M! MMM! MMMMMMMMMMMMMMMMMMMMM!! MM!     "
echo "      ! MMMMMMMMMMMMMMMMMMMMMMMM! !      "
echo "       MMMMMMMMMMMMMMMMMMMMMMMMM!!       "
echo "       MMMMMMMMMMMMMMMMMMMMMMMMMM!       "
echo "       MMMMM..    MMMMMM    .,MMM!       "
echo "       MMMM::   M.,MMMM,.M   ::M!!       "
echo "         MMM:::.,,MMMM!M,.::::!!         "
echo "        MMMMMMMMMMMMMM!!MMMMM!!M!        "
echo "        MMMMMMMMMMM:!!:!!MMMMMMM!        "
echo "         MMMMMMMMMMMMMMMMMMMMM!!         "
echo "            MMMMMMMMMMMMMMMM!            "
echo "          MM MMMMMMMMMMMMMM! MM          "
echo "         MMM! MMMMMMMMMMMMM MMMM         "
echo "    MMM.MMM!   M!!!!!!!!!M   MMMM MM!    "
echo "   MMMMMMM!    MMMMMMMMMMM    MMMMMM!    "
echo "     MMMMMM!    MMMMMMMMM    MMMMM!      "
echo "        MM!                   MM!"       "
pause